### PR TITLE
tools: fix cwd for workflow registrar to find installed workflows

### LINKED ISSUE #87: No workflows found in custom gateway generated by scaffold-gateway
**Description**
When you build a fresh custom gateway using `make scaffold-gateway` all workflows are missing.
**Expected Behavior**
The default workflows, as well as the `echo` workflow, should appear in clutch.
**Actual Behavior**
There are no workflows
Screenshot from 2020-07-23 18-14-05

**Version**
124f38193eb44cd29aad4d236fa32ef48ba30257

**Other Context**
I think this is because the workflows in https://github.com/lyft/clutch/blob/124f38193eb44cd29aad4d236fa32ef48ba30257/tools/scaffolding/templates/gateway/frontend/src/clutch.config.js#L2 are missing the proper `@clutch-sh` prefix
https://github.com/lyft/clutch/blob/124f38193eb44cd29aad4d236fa32ef48ba30257/frontend/packages/app/src/clutch.config.js#L2

### PR DESCRIPTION
**Pull request by dschaller**
### Description
The workflow registrar script should use the root of the src directory containing the `clutch.config.js` file to determine which workflow packages are installed.

### Testing Performed
Local.
```bash
$ node workflow-registrar.js /Users/dschaller/go/src/github.com/lyft/clutch/frontend/packages/app/src
Registered ec2 workflow...
Registered envoy workflow...
Registered k8s workflow...
Generated Workflow imports!
```

### GitHub Issue

Partially fixes #87

### CODE REVIEW

File: frontend/packages/tools/workflow-registrar.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ const discoverWorkflows = () => {
     return childProcess.exec(
       `yarn list --json --depth=0 --pattern '${packagePattern}'`,
       {
-        cwd: ".",
+        cwd: `${process.argv[2]}/..`,
```
Comment (danielhochman) [inline frontend/packages/tools/workflow-registrar.js:42]: can you pull it into a named var so it's clear what it is? a little terse otherwise.

Comment (danielhochman) [reply frontend/packages/tools/workflow-registrar.js:42]: comment is okay too
